// code/frontend/src/components/Chart.vue
<script>
import { Line, mixins } from 'vue-chartjs';
import axios from 'axios';

const { reactiveProp } = mixins;

export default {
  extends: Line,
  mixins: [reactiveProp],
  data() {
    return {
      selected: this.$router.currentRoute.params.selected,
      stockPrice: null,
      options: {
        responsive: true,
        maintainAspectRatio: false,
      },
    };
  },
  created() {
    this.getData();
  },
  methods: {
    back() {
      this.$router.push('/');
    },
    getData() {
      const path = 'http://127.0.0.1:5000/predict';
      console.log(path, this.selected);
      axios
        .get(path, {
          params: {
            ticker: this.selected,
          },
        })
        .then((response) => {
          this.stockPrice = response;
        })
        .catch((err) => {
          console.log(err);
        });
      // this.$router.push('/predict');
    },
  },
  computed: {
    chartdata() {
      return {

        // converted date string in the right format this way: https://www.codegrepper.com/code-examples/javascript/convert+timestamp+to+dd%2Fmm%2Fyyyy+in+javascript
        labels: Object.keys(JSON.parse(this.stockPrice.data.past_100_days))
          .map((a) => new Date(a / 1).toISOString().split('T')[0]),
        datasets: [{
          label: 'Stock Price',
          // backgroundColor: '#f87979',
          data: Object.values(JSON.parse(this.stockPrice.data.past_100_days)),
        }],
      };
    },
  },
  watch: {
    stockPrice() {
      // console.log('new',
      // JSON.parse(newValue.data.past_100_days),
      // this.chartdata, this.options, oldValue);
      this.renderChart(this.chartdata, this.options);
      // this.$data._chart.update();
    },
  },
};
</script>

// code/frontend_react/src/components/Chart.js
import React from 'react';
import { Chart as ChartJS, registerables } from 'chart.js';
// import { Chart } from 'react-chartjs-2'
import { Line } from 'react-chartjs-2';
import Box from '@mui/material/Box';

// chart template: https://www.educative.io/edpresso/how-to-use-chartjs-to-create-charts-in-react
function Chart(props) {
  // check this: https://stackoverflow.com/questions/67727603/error-category-is-not-a-registered-scale
  ChartJS.register(...registerables);
  console.log(props.data.result);
  const months = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sept',
    'Oct',
    'Nov',
    'Dec',
  ];

  const state = {
    // converted date string in the right format this way: https://www.codegrepper.com/code-examples/javascript/convert+timestamp+to+dd%2Fmm%2Fyyyy+in+javascript
    labels: Object.keys(JSON.parse(props.data.result.past_100_days))
      .map((a) => new Date(a / 1))
      .map((a) => `${a.getDate()} ${months[a.getMonth()]} ${a.getFullYear()}`),
    datasets: [
      {
        label: 'Stock Price',
        fill: false,
        lineTension: 0.5,
        backgroundColor: 'rgba(75,192,192,1)',
        borderColor: 'rgba(0,0,0,1)',
        borderWidth: 2,
        data: Object.values(JSON.parse(props.data.result.past_100_days)),
      },
    ],
  };
  return (
    <Box sx={{ width: '100%' }}>
      <Box>
        <Line
          data={state}
          options={{
            title: {
              display: true,
              text: 'Price of the stock in the previous 50 days',
              fontSize: 20,
            },
            legend: {
              display: true,
              position: 'right',
            },
          }}
        />
      </Box>
    </Box>
  );
}
export default Chart;
